Android 12 build support.
opengapps/opengapps pull request #959
Opened 2022-05-11 02:05 UTC by ipdev99

2022-05-11 02:09 UTC, ipdev99 commented
Since Android 9 (SDK28) Google stopped incremental builds.
_I could not find the article (might have been a page that Google changed/deleted/updated).
I may have missed bringing back incremental builds. :upside_down_face:_

Starting from SDK 28, each new level would be a new release level.
_Until 12L :upside_down_face:_

The build branch was updated to 12.1 when 12L was released but..

Platform codenames, versions, API levels, and NDK releases - [source.android](https://source.android.com/setup/start/build-numbers) has been updated a few times.
_When I started on 12L builds, it was not listed. Then it was listed as Android 12L when release.
Android 12L is now listed as version 12.1_

Android 12 (31) and 12L (32) still share the 12 release tag.
_12L still shows (May 2022 factory Pixel releases) as 12, not 12.1 or 12L_

I am not sure how to name it. :thinking:
_Stay with 12 and 12L or switch to 12.0 and 12.1_

Cheers. :cowboy_hat_face:

2022-05-14 15:46 UTC, flame-0 commented
I am wondering if I can use this now?

2022-05-14 23:56 UTC, josephcsible commented
Yes, via test builds posted at https://forum.xda-developers.com/t/gapps-daily-open-gapps-for-android-all-android-versions-devices.3098071/post-86595145

2022-05-29 09:07 UTC, mfonville commented
Thanks for your PR!

@nezorflame would the updated naming scheme with 12 and 12L work well with our website API for downloads?

2022-06-02 14:00 UTC, nezorflame commented
Thanks, I'll check this.

2022-06-11 17:41 UTC, mfonville commented
@nezorflame were you able to test the website compatibility?

2022-07-11 14:08 UTC, khalidtarek commented
Is this branch supporting Android 12 and 12L for x86_64? or for ARM only?
I am trying to add Gapps to the latest windows WSA using [WSAGAScript](https://github.com/WSA-Community/WSAGAScript) and when I check out this branch and perform 
./download_sources.sh --shallow x86_64
then  make x86_64-32-pico 
when I use the result image with the WSAGAScript it is causing the WSA to stuck at booting. so I am just checking if this should work for x86_64 architecture or only for arm

2022-08-08 22:36 UTC, AshiVered commented
There is an update? I need Open Gapps to Android 12 in his Stock ROM no GAPS ... I can to spoofing fingerprint, but I need OpenGaps ... thank you very much!

2022-09-03 01:48 UTC, Cortexian commented
Trying to include this in Windows Subsystem for Android and this is an issue. Unable to login, possible due to this.

2022-09-11 10:59 UTC, nezorflame approved these changes

2022-09-11 11:00 UTC, nezorflame commented
Think we can merge this now and enable in the build server settings.

2022-09-12 20:50 UTC, nezorflame commented
[Supported ](https://github.com/opengapps/package-api/pull/5)the change in the website's API as well

2022-10-01 18:31 UTC, PeterNjeim commented
Why was this PR closed?

2022-10-02 01:01 UTC, Howard20181 requested changes

2022-10-02 04:59 UTC, ipdev99 commented on scripts/build_gapps.sh
> +>>>>>>> 80e79a7 (Android 12 build support.)
I missed thatn one. :upside_down_face:

Fixed. :cowboy_hat_face:

2022-10-04 08:13 UTC, ThatBlockyPenguin commented
Just wondering how near this is to being merged - need this for OpenGApps on WSA

2022-10-05 11:45 UTC, s1204IT commented
Once this is merged, the [MindTheGappsBuilder](//github.com/s1204IT/MindTheGappsBuilder) I created will no longer be needed as the WSA's main GApps.

@mfonville Everyone is waiting for your reaction.

2022-10-08 11:43 UTC, mfonville commented
Sorry for my delay, was not available because of illness (combined with already full schedule).

Thanks for the rebase!

2022-10-08 11:43 UTC, merged

2022-10-15 12:10 UTC, nezorflame commented
@mfonville will you be able to enable the builds?

2022-10-27 20:22 UTC, amrf04 commented
Would also like to know when Android 12 will be available

2022-10-27 22:25 UTC, s1204IT commented
Until OpenGApps 12/12L is available, you will need to use other services such as MindTheGapps.
Especially users of WSA and LineageOS 19 and later are very keen on this.

2022-10-27 23:19 UTC, PeterNjeim commented
> Until OpenGApps 12/12L is available, you will need to use other services such as MindTheGapps.
> Especially users of WSA and LineageOS 19 and later are very keen on this.

Not true, you can build it yourself and it works. It's been working for several months for in [my repository](https://github.com/PeterNjeim/MagiskOnWSA), where I offer Full OpenGApps support. Understandably, making the API offer the builds is better and is the goal, however claiming that users "need" to use something else right now is simply not true

2022-10-27 23:31 UTC, s1204IT commented
@PeterNjeim You advertise your repository too much in various places.
I don't like it.
Each one of us can choose any means we like.

2022-10-27 23:48 UTC, PeterNjeim commented
> @PeterNjeim You advertise your repository too much in various places.
> I don't like it.
> Each one of us can choose any means we like.

That isn't a response to what I said. You also reacted negatively to one of comments via an emoji and I asked why, and you never replied. I don't like that.

And I'm not advertising, I'm giving concrete examples of how you can build it yourself. Please boil down my rebuttal to your statement to my mention of my repository, my point still stands, and I stand by it

2022-10-28 10:47 UTC, nezorflame commented
While true, we still need to support those who don't want to build them manually.
@mfonville any progress on the buildserver?

2022-10-28 11:09 UTC, slo617 commented
Of cause there is no law that forces anybody to do anything in open source projects. Everything is voluntary. (Never forget about that.)
Thank you for your work!
It would be very nice for the less-skilled part of the community and also for those how are busy with other projects if someone could update the build-servers.
Pretty please! ;)

2022-10-28 11:11 UTC, nezorflame commented
@slo617 yes, that's what I meant, @mfonville is in charge of the servers.

2022-10-28 11:19 UTC, mfonville commented
It is a bit of murphy's law at the moment. I was busy with de-odexing recent Android images to make sure we got the original and up-to-date sourced APKs. And already had little time for that available. Meanwhile the family is ill, so I am barely able to do any work at all, and on top of that is the physical machine that hosts the build-server offline at the moment, and its admin is abroad so he cannot look into it at the moment.

So I can only ask for some more patience...

2022-10-28 11:56 UTC, nezorflame commented
Sure thing, thank you for doing this and best wishes to the family ❤️

2022-12-08 03:03 UTC, bootsie123 commented
I hope you're doing better! Just curious to know if there are any updates on this

2022-12-08 10:24 UTC, nezorflame commented
We're going to deprecate our current buildserver and make everything
in-house from our main server.

Work is in progress for now so stay tuned for updates.

_____________________________

Best regards,
Ilya Danilkin

On Thu, Dec 8, 2022, 07:04 John Arrandale ***@***.***> wrote:

> I hope you're doing better! Just curious to know if there are any updates
> on this
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opengapps/opengapps/pull/959#issuecomment-1341917809>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA5ZZTTW4VWYHLXWKQU6PKDWMFF2VANCNFSM5VTLX2FQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-09 20:25 UTC, lorand-horvath commented
@nezorflame @mfonville I hope you're doing well! Just wanted to ask how is it going with the 12L builds... are you still having issues with the build server?